description: Any thing that is not a process or a physical mass-bearing entity
display_name: !!python/object/new:biolinkml.meta.ClassDefinitionName
- abstract entity
document_category: !!python/object/new:biolinkml.meta.ClassDefinitionName
- abstract entity
id: abstract_entity
schema_generating: true
weight: 20
