description: A relationship between two anatomical entities where the relationship
  is mereological, i.e the two entities are related by parthood. This includes relationships
  between cellular components and cells, between cells and tissues, tissues and whole
  organisms
display_name: anatomical entity to anatomical entity part of association
document_category: anatomical entity to anatomical entity part of association
fields:
- display_name: anatomical entity to anatomical entity part of association_subject
  id: subject
- display_name: anatomical entity to anatomical entity part of association_relation
  id: relation
- display_name: anatomical entity to anatomical entity part of association_object
  id: object
- description: A unique identifier for an association
  display_name: association_id
  id: id
- description: if set to true, then the association is negated i.e. is not true
  display_name: negated
  id: negated
- description: connects an association to the type of association (e.g. gene to phenotype)
  display_name: association type
  id: association_type
- cardinality: multi
  description: connects an association to qualifiers that modify or qualify the meaning
    of that association
  display_name: qualifiers
  id: qualifiers
- cardinality: multi
  description: connects an association to publications supporting the association
  display_name: publications
  id: publications
- description: connects an association to the agent (person, organization or group)
    that provided it
  display_name: provided by
  id: provided_by
- description: any slot that relates an association to another entity
  display_name: association slot
  id: association_slot
- description: A high-level grouping for the relationship type. AKA minimal predicate.
    This is analogous to category for nodes.
  display_name: edge label
  id: edge_label
id: anatomical_entity_to_anatomical_entity_part_of_association
schema_generating: true
weight: 20
