id: anatomical_entity
schema_generating: true
description: A subcellular location, cell type or gross anatomical part
display_name: anatomical entity
document_category: anatomical entity
weight: 20
fields:
- id: id
  description: A unique identifier for an entity. Must be either a CURIE shorthand
    for a URI or a complete URI
  display_name: id
- id: iri
  description: An IRI for an entity. This is determined by the id using expansion
    rules.
  display_name: iri
- id: type
  display_name: type
- id: name
  description: A human-readable name for an attribute or entity.
  display_name: name
- id: description
  description: a human-readable description of an entity
  display_name: description
- id: source
  description: a lightweight analog to the association class 'has provider' slot,
    which is the string name, or the authoritative (i.e. database) namespace, designating
    the origin of the entity to which the slot belongs.
  display_name: source
- id: provided_by
  description: connects an association to the agent (person, organization or group)
    that provided it
  display_name: provided by
  cardinality: multi
- id: category
  display_name: named thing_category
  cardinality: multi
- id: has_attribute
  description: may often be an organism attribute
  display_name: organismal entity_has attribute
  cardinality: multi
- id: in_taxon
  description: connects an entity to its taxonomic classification. Only certain kinds
    of entities can be taxonomically classified; see 'thing with taxon'
  display_name: in taxon
  cardinality: multi
