description: A typed association between two entities, supported by evidence
display_name: !!python/object/new:biolinkml.meta.ClassDefinitionName
- association
document_category: !!python/object/new:biolinkml.meta.ClassDefinitionName
- association
fields:
- description: connects an association to the subject of the association. For example,
    in a gene-to-phenotype association, the gene is subject and phenotype is object.
  display_name: !!python/object/new:biolinkml.meta.SlotDefinitionName
  - subject
  id: subject
- description: the relationship type by which a subject is connected to an object
    in an association
  display_name: !!python/object/new:biolinkml.meta.SlotDefinitionName
  - relation
  id: relation
- description: connects an association to the object of the association. For example,
    in a gene-to-phenotype association, the gene is subject and phenotype is object.
  display_name: !!python/object/new:biolinkml.meta.SlotDefinitionName
  - object
  id: object
- description: A unique identifier for an association
  display_name: !!python/object/new:biolinkml.meta.SlotDefinitionName
  - association_id
  id: id
- description: if set to true, then the association is negated i.e. is not true
  display_name: !!python/object/new:biolinkml.meta.SlotDefinitionName
  - negated
  id: negated
- description: connects an association to the type of association (e.g. gene to phenotype)
  display_name: !!python/object/new:biolinkml.meta.SlotDefinitionName
  - association type
  id: association_type
- cardinality: multi
  description: connects an association to qualifiers that modify or qualify the meaning
    of that association
  display_name: !!python/object/new:biolinkml.meta.SlotDefinitionName
  - qualifiers
  id: qualifiers
- cardinality: multi
  description: connects an association to publications supporting the association
  display_name: !!python/object/new:biolinkml.meta.SlotDefinitionName
  - publications
  id: publications
- description: connects an association to the agent (person, organization or group)
    that provided it
  display_name: !!python/object/new:biolinkml.meta.SlotDefinitionName
  - provided by
  id: provided_by
- description: any slot that relates an association to another entity
  display_name: !!python/object/new:biolinkml.meta.SlotDefinitionName
  - association slot
  id: association_slot
- description: A high-level grouping for the relationship type. AKA minimal predicate.
    This is analogous to category for nodes.
  display_name: !!python/object/new:biolinkml.meta.SlotDefinitionName
  - edge label
  id: edge_label
- description: connects an association to a qualitative term denoting the level of
    confidence
  display_name: !!python/object/new:biolinkml.meta.SlotDefinitionName
  - has confidence level
  id: has_confidence_level
- description: connects an association to an instance of supporting evidence
  display_name: !!python/object/new:biolinkml.meta.SlotDefinitionName
  - has evidence
  id: has_evidence
- description: stage at which expression takes place
  display_name: !!python/object/new:biolinkml.meta.SlotDefinitionName
  - stage qualifier
  id: stage_qualifier
- description: A measurable quantity for the object of the association
  display_name: !!python/object/new:biolinkml.meta.SlotDefinitionName
  - quantifier qualifier
  id: quantifier_qualifier
- description: a qualifier used in a phenotypic association to state how frequent
    the phenotype is observed in the subject
  display_name: !!python/object/new:biolinkml.meta.SlotDefinitionName
  - frequency qualifier
  id: frequency_qualifier
- description: a qualifier used in a phenotypic association to state how severe the
    phenotype is in the subject
  display_name: !!python/object/new:biolinkml.meta.SlotDefinitionName
  - severity qualifier
  id: severity_qualifier
- description: a qualifier used in a phenotypic association to state whether the association
    is specific to a particular sex.
  display_name: !!python/object/new:biolinkml.meta.SlotDefinitionName
  - sex qualifier
  id: sex_qualifier
- description: a qualifier used in a phenotypic association to state when the phenotype
    appears is in the subject
  display_name: !!python/object/new:biolinkml.meta.SlotDefinitionName
  - onset qualifier
  id: onset_qualifier
- description: Used to characterize and specify the phenotypic abnormalities defined
    in the Phenotypic abnormality subontology, with respect to severity, laterality,
    age of onset, and other aspects
  display_name: !!python/object/new:biolinkml.meta.SlotDefinitionName
  - clinical modifier qualifier
  id: clinical_modifier_qualifier
- description: a qualifier used in an association where the variant
  display_name: !!python/object/new:biolinkml.meta.SlotDefinitionName
  - sequence variant qualifier
  id: sequence_variant_qualifier
- cardinality: multi
  description: hyperedge connecting an association between two causally connected
    entities (for example, two chemical entities, or a chemical entity in that changes
    location) and the gene product, gene, or complex that enables or catalyzes the
    change.
  display_name: !!python/object/new:biolinkml.meta.SlotDefinitionName
  - change is catalyzed by
  id: change_is_catalyzed_by
id: association
schema_generating: true
weight: 20
