id: biotic_exposure
schema_generating: true
description: An external biotic exposure is an intake of (sometimes pathological)
  biological organisms (including viruses).
display_name: biotic exposure
document_category: biotic exposure
weight: 20
fields:
- id: id
  description: A unique identifier for an entity. Must be either a CURIE shorthand
    for a URI or a complete URI
  display_name: id
- id: iri
  description: An IRI for an entity. This is determined by the id using expansion
    rules.
  display_name: iri
- id: type
  display_name: type
- id: name
  description: A human-readable name for an attribute or entity.
  display_name: name
- id: description
  description: a human-readable description of an entity
  display_name: description
- id: source
  description: a lightweight analog to the association class 'has provider' slot,
    which is the string name, or the authoritative (i.e. database) namespace, designating
    the origin of the entity to which the slot belongs.
  display_name: source
- id: provided_by
  description: connects an association to the agent (person, organization or group)
    that provided it
  display_name: provided by
  cardinality: multi
- id: has_attribute
  description: connects any entity to an attribute
  display_name: has attribute
  cardinality: multi
- id: category
  display_name: named thing_category
  cardinality: multi
- id: has_taxonomic_rank
  display_name: organism taxon_has taxonomic rank
- id: subclass_of
  description: subclass of holds between two taxa, e.g. human subclass of mammal
  display_name: organism taxon_subclass of
  cardinality: multi
- id: timepoint
  description: a point in time
  display_name: timepoint
