id: chemical_mixture
schema_generating: true
description: A chemical mixture is a chemical entity composed of two or more molecular
  entities.
display_name: chemical mixture
document_category: chemical mixture
weight: 20
fields:
- id: id
  description: A unique identifier for an entity. Must be either a CURIE shorthand
    for a URI or a complete URI
  display_name: id
- id: iri
  description: An IRI for an entity. This is determined by the id using expansion
    rules.
  display_name: iri
- id: type
  display_name: type
- id: name
  description: A human-readable name for an attribute or entity.
  display_name: name
- id: description
  description: a human-readable description of an entity
  display_name: description
- id: source
  description: a lightweight analog to the association class 'has provider' slot,
    which is the string name, or the authoritative (i.e. database) namespace, designating
    the origin of the entity to which the slot belongs.
  display_name: source
- id: provided_by
  description: connects an association to the agent (person, organization or group)
    that provided it
  display_name: provided by
  cardinality: multi
- id: has_attribute
  description: connects any entity to an attribute
  display_name: has attribute
  cardinality: multi
- id: category
  display_name: named thing_category
  cardinality: multi
- id: trade_name
  description: ''
  display_name: trade name
- id: available_from
  description: ''
  display_name: available from
  cardinality: multi
- id: is_supplement
  description: ''
  display_name: is supplement
- id: highest_FDA_approval_status
  description: Should be the highest level of FDA approval this chemical entity or
    device has, regardless of which disease, condition or phenotype it is currently
    being reviewed to treat.  For specific levels of FDA approval for a specific condition,
    disease, phenotype, etc., see the association slot, 'FDA approval status.'
  display_name: highest FDA approval status
