description: An interaction between a chemical entity and a biological process or
  pathway
display_name: chemical to pathway association
document_category: chemical to pathway association
fields:
- description: connects an association to the subject of the association. For example,
    in a gene-to-phenotype association, the gene is subject and phenotype is object.
  display_name: subject
  id: subject
- description: the relationship type by which a subject is connected to an object
    in an association
  display_name: relation
  id: relation
- display_name: chemical to pathway association_object
  id: object
- description: A unique identifier for an association
  display_name: association_id
  id: id
- description: if set to true, then the association is negated i.e. is not true
  display_name: negated
  id: negated
- description: connects an association to the type of association (e.g. gene to phenotype)
  display_name: association type
  id: association_type
- cardinality: multi
  description: connects an association to qualifiers that modify or qualify the meaning
    of that association
  display_name: qualifiers
  id: qualifiers
- cardinality: multi
  description: connects an association to publications supporting the association
  display_name: publications
  id: publications
- description: connects an association to the agent (person, organization or group)
    that provided it
  display_name: provided by
  id: provided_by
- description: any slot that relates an association to another entity
  display_name: association slot
  id: association_slot
- description: A high-level grouping for the relationship type. AKA minimal predicate.
    This is analogous to category for nodes.
  display_name: edge label
  id: edge_label
id: chemical_to_pathway_association
schema_generating: true
weight: 20
