id: clinical_measurement
schema_generating: true
description: A clinical measurement is a special kind of attribute which results from
  a laboratory observation from a subject individual or sample. Measurements can be
  connected to their subject by the 'has attribute' slot.
display_name: clinical measurement
document_category: clinical measurement
weight: 20
fields:
- id: name
  description: The human-readable 'attribute name' can be set to a string which reflects
    its context of interpretation, e.g. SEPIO evidence/provenance/confidence annotation
    or it can default to the name associated with the 'has attribute type' slot ontology
    term.
  display_name: attribute_name
- id: has_quantitative_value
  description: connects an attribute to a value
  display_name: has quantitative value
  cardinality: multi
- id: has_qualitative_value
  description: connects an attribute to a value
  display_name: has qualitative value
- id: iri
  description: An IRI for an entity. This is determined by the id using expansion
    rules.
  display_name: iri
- id: source
  description: a lightweight analog to the association class 'has provider' slot,
    which is the string name, or the authoritative (i.e. database) namespace, designating
    the origin of the entity to which the slot belongs.
  display_name: source
- id: has_attribute_type
  display_name: clinical measurement_has attribute type
