id: drug_to_gene_interaction_exposure
schema_generating: true
description: drug to gene interaction exposure is a drug exposure is where the interactions
  of the drug with specific genes are known to constitute an 'exposure' to the organism,
  leading to or influencing an outcome.
display_name: drug to gene interaction exposure
document_category: drug to gene interaction exposure
weight: 20
fields:
- id: timepoint
  description: a point in time
  display_name: timepoint
- id: has_gene_or_gene_product
  description: connects an entity with one or more gene or gene products
  display_name: has gene or gene product
  cardinality: multi
