id: frequency_qualifier_mixin
schema_generating: true
description: Qualifier for frequency type associations
display_name: frequency qualifier mixin
document_category: frequency qualifier mixin
weight: 20
fields:
- id: frequency_qualifier
  description: a qualifier used in a phenotypic association to state how frequent
    the phenotype is observed in the subject
  display_name: frequency qualifier
