id: frequency_quantifier
schema_generating: true
display_name: frequency quantifier
document_category: frequency quantifier
weight: 20
fields:
- id: has_count
  description: number of things with a particular property
  display_name: has count
- id: has_total
  description: total number of things in a particular reference set
  display_name: has total
- id: has_quotient
  display_name: has quotient
- id: has_percentage
  description: equivalent to has quotient multiplied by 100
  display_name: has percentage
