id: gene_expression_mixin
schema_generating: true
description: Observed gene expression intensity, context (site, stage) and associated
  phenotypic status within which the expression occurs.
display_name: gene expression mixin
document_category: gene expression mixin
weight: 20
fields:
- id: quantifier_qualifier
  description: Optional quantitative value indicating degree of expression.
  display_name: gene expression mixin_quantifier qualifier
- id: expression_site
  description: location in which gene or protein expression takes place. May be cell,
    tissue, or organ.
  display_name: expression site
- id: stage_qualifier
  description: stage during which gene or protein expression of takes place.
  display_name: stage qualifier
- id: phenotypic_state
  description: in experiments (e.g. gene expression) assaying diseased or unhealthy
    tissue, the phenotypic state can be put here, e.g. MONDO ID. For healthy tissues,
    use XXX.
  display_name: phenotypic state
