display_name: !!python/object/new:metamodel.metamodel.ClassDefinitionName [gene has
    variant that contributes to disease association]
document_category: !!python/object/new:metamodel.metamodel.ClassDefinitionName [gene
    has variant that contributes to disease association]
fields:
- description: A unique identifier for an association
  display_name: !!python/object/new:metamodel.metamodel.SlotDefinitionName [association_id]
  id: id
- description: the relationship type by which a subject is connected to an object
    in an association
  display_name: !!python/object/new:metamodel.metamodel.SlotDefinitionName [relation]
  id: relation
- description: connects an association to the object of the association. For example,
    in a gene-to-phenotype association, the gene is subject and phenotype is object.
  display_name: !!python/object/new:metamodel.metamodel.SlotDefinitionName [object]
  id: object
- description: if set to true, then the association is negated i.e. is not true
  display_name: !!python/object/new:metamodel.metamodel.SlotDefinitionName [negated]
  id: negated
- description: connects an association to the type of association (e.g. gene to phenotype)
  display_name: !!python/object/new:metamodel.metamodel.SlotDefinitionName [association
      type]
  id: association_type
- cardinality: multi
  description: connects an association to qualifiers that modify or qualify the meaning
    of that association
  display_name: !!python/object/new:metamodel.metamodel.SlotDefinitionName [qualifiers]
  id: qualifiers
- cardinality: multi
  description: connects an association to publications supporting the association
  display_name: !!python/object/new:metamodel.metamodel.SlotDefinitionName [publications]
  id: publications
- description: connects an association to the agent (person, organization or group)
    that provided it
  display_name: !!python/object/new:metamodel.metamodel.SlotDefinitionName [provided
      by]
  id: provided_by
- description: any slot that relates an association to another entity
  display_name: !!python/object/new:metamodel.metamodel.SlotDefinitionName [association
      slot]
  id: association_slot
- description: a qualifier used in a phenotypic association to state how severe the
    phenotype is in the subject
  display_name: !!python/object/new:metamodel.metamodel.SlotDefinitionName [severity
      qualifier]
  id: severity_qualifier
- description: a qualifier used in a phenotypic association to state when the phenotype
    appears is in the subject
  display_name: !!python/object/new:metamodel.metamodel.SlotDefinitionName [onset
      qualifier]
  id: onset_qualifier
- description: a qualifier used in an association where the variant
  display_name: !!python/object/new:metamodel.metamodel.SlotDefinitionName [sequence
      variant qualifier]
  id: sequence_variant_qualifier
- description: A gene that has a role in modeling the disease. This may be a model
    organism ortholog of a known disease gene, or it may be a gene whose mutants recapitulate
    core features of the disease.
  display_name: !!python/object/new:metamodel.metamodel.SlotDefinitionName [gene has
      variant that contributes to disease association subject]
  id: subject
id: gene_has_variant_that_contributes_to_disease_association
schema_generating: true
weight: 20
