id: gene_has_variant_that_contributes_to_disease_association
schema_generating: true
display_name: gene has variant that contributes to disease association
document_category: gene has variant that contributes to disease association
weight: 20
fields:
- id: id
  description: A unique identifier for an entity. Must be either a CURIE shorthand
    for a URI or a complete URI
  display_name: id
- id: iri
  description: An IRI for an entity. This is determined by the id using expansion
    rules.
  display_name: iri
- id: name
  description: A human-readable name for an attribute or entity.
  display_name: name
- id: description
  description: a human-readable description of an entity
  display_name: description
- id: source
  description: a lightweight analog to the association class 'has provider' slot,
    which is the string name, or the authoritative (i.e. database) namespace, designating
    the origin of the entity to which the slot belongs.
  display_name: source
- id: provided_by
  description: connects an association to the agent (person, organization or group)
    that provided it
  display_name: provided by
  cardinality: multi
- id: has_attribute
  description: connects any entity to an attribute
  display_name: has attribute
  cardinality: multi
- id: predicate
  description: A high-level grouping for the relationship type. AKA minimal predicate.
    This is analogous to category for nodes.
  display_name: predicate
- id: object
  description: connects an association to the object of the association. For example,
    in a gene-to-phenotype association, the gene is subject and phenotype is object.
  display_name: object
- id: relation
  description: The relation which describes an association between a subject and an
    object in a more granular manner. Usually this is a term from Relation Ontology,
    but it can be any edge CURIE.
  display_name: relation
- id: negated
  description: if set to true, then the association is negated i.e. is not true
  display_name: negated
- id: qualifiers
  description: connects an association to qualifiers that modify or qualify the meaning
    of that association
  display_name: qualifiers
  cardinality: multi
- id: publications
  description: connects an association to publications supporting the association
  display_name: publications
  cardinality: multi
- id: type
  description: rdf:type of biolink:Association should be fixed at rdf:Statement
  display_name: association_type
- id: category
  display_name: association_category
  cardinality: multi
- id: frequency_qualifier
  description: a qualifier used in a phenotypic association to state how frequent
    the phenotype is observed in the subject
  display_name: frequency qualifier
- id: severity_qualifier
  description: a qualifier used in a phenotypic association to state how severe the
    phenotype is in the subject
  display_name: severity qualifier
- id: onset_qualifier
  description: a qualifier used in a phenotypic association to state when the phenotype
    appears is in the subject
  display_name: onset qualifier
- id: sequence_variant_qualifier
  description: a qualifier used in an association with the variant
  display_name: sequence variant qualifier
- id: subject
  description: A gene that has a role in modeling the disease. This may be a model
    organism ortholog of a known disease gene, or it may be a gene whose mutants recapitulate
    core features of the disease.
  display_name: gene has variant that contributes to disease association_subject
