id: gene_or_gene_product
schema_generating: true
description: a union of genes or gene products. Frequently an identifier for one will
  be used as proxy for another
display_name: gene or gene product
document_category: gene or gene product
weight: 20
fields:
- id: id
  description: A unique identifier for an entity. Must be either a CURIE shorthand
    for a URI or a complete URI
  display_name: id
- id: iri
  description: An IRI for an entity. This is determined by the id using expansion
    rules.
  display_name: iri
- id: type
  display_name: type
- id: description
  description: a human-readable description of an entity
  display_name: description
- id: source
  description: a lightweight analog to the association class 'has provider' slot,
    which is the string name, or the authoritative (i.e. database) namespace, designating
    the origin of the entity to which the slot belongs.
  display_name: source
- id: provided_by
  description: connects an association to the agent (person, organization or group)
    that provided it
  display_name: provided by
  cardinality: multi
- id: has_attribute
  description: connects any entity to an attribute
  display_name: has attribute
  cardinality: multi
- id: category
  display_name: named thing_category
  cardinality: multi
- id: in_taxon
  description: connects an entity to its taxonomic classification. Only certain kinds
    of entities can be taxonomically classified; see 'thing with taxon'
  display_name: in taxon
  cardinality: multi
- id: has_biological_sequence
  description: connects a genomic feature to its sequence
  display_name: has biological sequence
- id: name
  description: genes are typically designated by a short symbol and a full name. We
    map the symbol to the default display name and use an additional slot for full
    name
  display_name: macromolecular machine_name
