id: genomic_sequence_localization
schema_generating: true
description: A relationship between a sequence feature and a genomic entity it is
  localized to. The reference entity may be a chromosome, chromosome region or information
  entity such as a contig.
display_name: genomic sequence localization
document_category: genomic sequence localization
weight: 20
fields:
- id: id
  description: A unique identifier for an entity. Must be either a CURIE shorthand
    for a URI or a complete URI
  display_name: id
- id: iri
  description: An IRI for an entity. This is determined by the id using expansion
    rules.
  display_name: iri
- id: name
  description: A human-readable name for an attribute or entity.
  display_name: name
- id: description
  description: a human-readable description of an entity
  display_name: description
- id: source
  description: a lightweight analog to the association class 'has provider' slot,
    which is the string name, or the authoritative (i.e. database) namespace, designating
    the origin of the entity to which the slot belongs.
  display_name: source
- id: provided_by
  description: connects an association to the agent (person, organization or group)
    that provided it
  display_name: provided by
  cardinality: multi
- id: has_attribute
  description: connects any entity to an attribute
  display_name: has attribute
  cardinality: multi
- id: relation
  description: The relation which describes an association between a subject and an
    object in a more granular manner. Usually this is a term from Relation Ontology,
    but it can be any edge CURIE.
  display_name: relation
- id: negated
  description: if set to true, then the association is negated i.e. is not true
  display_name: negated
- id: qualifiers
  description: connects an association to qualifiers that modify or qualify the meaning
    of that association
  display_name: qualifiers
  cardinality: multi
- id: publications
  description: connects an association to publications supporting the association
  display_name: publications
  cardinality: multi
- id: type
  description: rdf:type of biolink:Association should be fixed at rdf:Statement
  display_name: association_type
- id: category
  display_name: association_category
  cardinality: multi
- id: start_interbase_coordinate
  description: The position at which the subject genomic entity starts on the chromosome
    or other entity to which it is located on.
  display_name: start interbase coordinate
- id: end_interbase_coordinate
  description: The position at which the subject genomic entity ends on the chromosome
    or other entity to which it is located on.
  display_name: end interbase coordinate
- id: genome_build
  description: The version of the genome on which a feature is located. For example,
    GRCh38 for Homo sapiens.
  display_name: genome build
- id: strand
  description: The strand on which a feature is located. Has a value of '+' (sense
    strand or forward strand) or '-' (anti-sense strand or reverse strand).
  display_name: strand
- id: phase
  description: The phase for a coding sequence entity. For example, phase of a CDS
    as represented in a GFF3 with a value of 0, 1 or 2.
  display_name: phase
- id: subject
  display_name: genomic sequence localization_subject
- id: object
  display_name: genomic sequence localization_object
- id: predicate
  display_name: genomic sequence localization_predicate
