description: A sample is a limited quantity of something (e.g. an individual or set
  of individuals from a population, or a portion of a substance) to be used for testing,
  analysis, inspection, investigation, demonstration, or trial use. [SIO]
display_name: material sample
document_category: material sample
fields:
- description: A unique identifier for a thing. Must be either a CURIE shorthand for
    a URI or a complete URI
  display_name: id
  id: id
- description: A human-readable name for a thing
  display_name: name
  id: name
- cardinality: multi
  description: Name of the high level ontology class in which this entity is categorized.
    Corresponds to the label for the biolink entity type class. In a neo4j database
    this MAY correspond to the neo4j label tag
  display_name: category
  id: category
- cardinality: multi
  description: A relationship that is asserted between two named things
  display_name: related to
  id: related_to
- cardinality: multi
  description: holds between any two entities that directly or indirectly interact
    with each other
  display_name: interacts with
  id: interacts_with
- description: A grouping for any property that holds between a node and a value
  display_name: node property
  id: node_property
- description: An IRI for the node. This is determined by the id using expansion rules.
  display_name: iri
  id: iri
- cardinality: multi
  description: Alternate human-readable names for a thing
  display_name: synonym
  id: synonym
- description: a long-form human readable name for a thing
  display_name: full name
  id: full_name
- description: a human-readable description of a thing
  display_name: description
  id: description
- cardinality: multi
  description: more commonly used for gene symbols in yeast
  display_name: systematic synonym
  id: systematic_synonym
- cardinality: multi
  description: connects any named thing to an attribute
  display_name: has attribute
  id: has_attribute
id: material_sample
schema_generating: true
weight: 20
