description: An association between a material sample and the material entity it is
  derived from
display_name: !!python/object/new:biolinkml.meta.ClassDefinitionName
- material sample derivation association
document_category: !!python/object/new:biolinkml.meta.ClassDefinitionName
- material sample derivation association
fields:
- display_name: !!python/object/new:biolinkml.meta.SlotDefinitionName
  - material sample derivation association_subject
  id: subject
- display_name: !!python/object/new:biolinkml.meta.SlotDefinitionName
  - material sample derivation association_relation
  id: relation
- display_name: !!python/object/new:biolinkml.meta.SlotDefinitionName
  - material sample derivation association_object
  id: object
- description: A unique identifier for an association
  display_name: !!python/object/new:biolinkml.meta.SlotDefinitionName
  - association_id
  id: id
- description: if set to true, then the association is negated i.e. is not true
  display_name: !!python/object/new:biolinkml.meta.SlotDefinitionName
  - negated
  id: negated
- description: connects an association to the type of association (e.g. gene to phenotype)
  display_name: !!python/object/new:biolinkml.meta.SlotDefinitionName
  - association type
  id: association_type
- cardinality: multi
  description: connects an association to qualifiers that modify or qualify the meaning
    of that association
  display_name: !!python/object/new:biolinkml.meta.SlotDefinitionName
  - qualifiers
  id: qualifiers
- cardinality: multi
  description: connects an association to publications supporting the association
  display_name: !!python/object/new:biolinkml.meta.SlotDefinitionName
  - publications
  id: publications
- description: connects an association to the agent (person, organization or group)
    that provided it
  display_name: !!python/object/new:biolinkml.meta.SlotDefinitionName
  - provided by
  id: provided_by
- description: any slot that relates an association to another entity
  display_name: !!python/object/new:biolinkml.meta.SlotDefinitionName
  - association slot
  id: association_slot
- description: A high-level grouping for the relationship type. AKA minimal predicate.
    This is analogous to category for nodes.
  display_name: !!python/object/new:biolinkml.meta.SlotDefinitionName
  - edge label
  id: edge_label
id: material_sample_derivation_association
schema_generating: true
weight: 20
