id: molecular_activity
schema_generating: true
description: An execution of a molecular function carried out by a gene product or
  macromolecular complex.
display_name: molecular activity
document_category: molecular activity
weight: 20
fields:
- id: id
  description: A unique identifier for a thing. Must be either a CURIE shorthand for
    a URI or a complete URI
  display_name: id
- id: name
  description: A human-readable name for a thing
  display_name: name
- id: category
  description: "Name of the high level ontology class in which this entity is categorized.\
    \ Corresponds to the label for the biolink entity type class.\n * In a neo4j database\
    \ this MAY correspond to the neo4j label tag.\n * In an RDF database it should\
    \ be a biolink model class URI.\nThis field is multi-valued. It should include\
    \ values for ancestors of the biolink class; for example, a protein such as Shh\
    \ would have category values `bl:Protein`, `bl:GeneProduct`, `bl:MolecularEntity`,\
    \ ...\nIn an RDF database, nodes will typically have an rdf:type triples. This\
    \ can be to the most specific biolink class, or potentially to a class more specific\
    \ than something in biolink. For example, a sequence feature `f` may have a rdf:type\
    \ assertion to a SO class such as TF_binding_site, which is more specific than\
    \ anything in biolink. Here we would have categories {bl:GenomicEntity, bl:MolecularEntity,\
    \ bl:NamedThing}"
  display_name: category
  cardinality: multi
- id: has_input
  description: A chemical entity that is the input for the reaction
  display_name: molecular activity_has input
  cardinality: multi
- id: has_output
  description: A chemical entity that is the output for the reaction
  display_name: molecular activity_has output
  cardinality: multi
- id: enabled_by
  description: The gene product, gene, or complex that catalyzes the reaction
  display_name: molecular activity_enabled by
  cardinality: multi
