description: A value of an attribute that is quantitative and measurable, expressed
  as a combination of a unit and a numeric value
display_name: quantity value
document_category: quantity value
fields:
- description: connects a quantity value to a unit
  display_name: has unit
  id: has_unit
- description: connects a quantity value to a number
  display_name: has numeric value
  id: has_numeric_value
id: quantity_value
schema_generating: true
weight: 20
