id: serial
schema_generating: true
description: This class may rarely be instantiated except if use cases of a given
  knowledge graph support its utility.
display_name: serial
document_category: serial
weight: 20
fields:
- id: category
  description: "Name of the high level ontology class in which this entity is categorized.\
    \ Corresponds to the label for the biolink entity type class.\n * In a neo4j database\
    \ this MAY correspond to the neo4j label tag.\n * In an RDF database it should\
    \ be a biolink model class URI.\nThis field is multi-valued. It should include\
    \ values for ancestors of the biolink class; for example, a protein such as Shh\
    \ would have category values `bl:Protein`, `bl:GeneProduct`, `bl:MolecularEntity`,\
    \ ...\nIn an RDF database, nodes will typically have an rdf:type triples. This\
    \ can be to the most specific biolink class, or potentially to a class more specific\
    \ than something in biolink. For example, a sequence feature `f` may have a rdf:type\
    \ assertion to a SO class such as TF_binding_site, which is more specific than\
    \ anything in biolink. Here we would have categories {bl:GenomicEntity, bl:MolecularEntity,\
    \ bl:NamedThing}"
  display_name: category
  cardinality: multi
- id: description
  description: a human-readable description of a thing
  display_name: description
- id: license
  display_name: license
- id: rights
  display_name: rights
- id: format
  display_name: format
- id: creation_date
  description: date on which thing was created. This can be applied to nodes or edges
  display_name: creation date
- id: authors
  description: connects an publication to the list of authors who contributed to the
    publication. This property should be a comma-delimited list of author names. It
    is recommended that an author's name be formatted as "surname, firstname initial.".   Note
    that this property is a node annotation expressing the citation list of authorship
    which might typically otherwise be more completely documented in biolink:PublicationToProviderAssociation
    defined edges which point to full details about an author and possibly, some qualifiers
    which clarify the specific status of a given author in the publication.
  display_name: authors
  cardinality: multi
- id: pages
  description: When a 2-tuple of page numbers are provided, they represent the start
    and end page of the publication within its parent publication context. For books,
    this may be set to the total number of pages of the book.
  display_name: publication_pages
  cardinality: multi
- id: summary
  description: executive  summary of a publication
  display_name: summary
- id: keywords
  description: keywords tagging a publication
  display_name: keywords
  cardinality: multi
- id: mesh_terms
  description: mesh terms tagging a publication
  display_name: mesh terms
  cardinality: multi
- id: xref
  description: Alternate CURIEs for a thing
  display_name: xref
  cardinality: multi
- id: name
  description: the 'title' of the publication is generally recorded in the 'name'
    property (inherited from NamedThing) The field name 'title' is now also tagged
    as an acceptable alias for the node property 'name' (just in case).
  display_name: publication_name
- id: iso_abbreviation
  description: Standard abbreviation for periodicals in the International Organization
    for Standardization (ISO) 4 system See https://www.issn.org/services/online-services/access-to-the-ltwa/.
    If the 'published in' property is set, then the iso abbreviation pertains to the
    broader publication context (the journal) within which the given publication node
    is embedded, not the publication itself.
  display_name: iso abbreviation
- id: volume
  description: volume of a book or music release in a collection/series or a published
    collection of journal issues in a serial publication
  display_name: volume
- id: issue
  description: issue of a newspaper, a scientific journal or magazine for reference
    purpose
  display_name: issue
- id: id
  description: Serials (journals) should have industry-standard identifier such as
    from ISSN.
  display_name: serial_id
- id: type
  description: Should generally be set to an ontology class defined term for 'serial'
    or 'journal'.
  display_name: serial_type
