id: taxonomic_rank
schema_generating: true
description: 'A descriptor for the rank within a taxonomic classification. Example
  instance: TAXRANK:0000017 (kingdom)'
display_name: taxonomic rank
document_category: taxonomic rank
weight: 20
