id: variant_as_a_model_of_disease_association
schema_generating: true
display_name: variant as a model of disease association
document_category: variant as a model of disease association
weight: 20
fields:
- id: id
  description: A unique identifier for an association
  display_name: association_id
- id: association_type
  description: connects an association to the type of association (e.g. gene to phenotype)
  display_name: association type
- id: predicate
  description: A high-level grouping for the relationship type. AKA minimal predicate.
    This is analogous to category for nodes.
  display_name: predicate
- id: negated
  description: if set to true, then the association is negated i.e. is not true
  display_name: negated
- id: qualifiers
  description: connects an association to qualifiers that modify or qualify the meaning
    of that association
  display_name: qualifiers
  cardinality: multi
- id: publications
  description: connects an association to publications supporting the association
  display_name: publications
  cardinality: multi
- id: provided_by
  description: connects an association to the agent (person, organization or group)
    that provided it
  display_name: provided by
  cardinality: multi
- id: relation
  description: E.g. is pathogenic for
  display_name: variant to disease association_relation
- id: object
  description: a disease that is associated with that variant
  display_name: variant to disease association_object
- id: frequency_qualifier
  description: a qualifier used in a phenotypic association to state how frequent
    the phenotype is observed in the subject
  display_name: frequency qualifier
- id: severity_qualifier
  description: a qualifier used in a phenotypic association to state how severe the
    phenotype is in the subject
  display_name: severity qualifier
- id: onset_qualifier
  description: a qualifier used in a phenotypic association to state when the phenotype
    appears is in the subject
  display_name: onset qualifier
- id: subject
  description: A variant that has a role in modeling the disease.
  display_name: variant as a model of disease association_subject
