description: Either one of a disease or an individual phenotypic feature. Some knowledge
  resources such as Monarch treat these as distinct, others such as MESH conflate.
display_name: !!python/object/new:metamodel.metamodel.ClassDefinitionName [disease
    or phenotypic feature]
document_category: !!python/object/new:metamodel.metamodel.ClassDefinitionName [disease
    or phenotypic feature]
fields:
- description: A unique identifier for a thing. Must be either a CURIE shorthand for
    a URI or a complete URI
  display_name: !!python/object/new:metamodel.metamodel.SlotDefinitionName [id]
  id: id
- description: A human-readable name for a thing
  display_name: !!python/object/new:metamodel.metamodel.SlotDefinitionName [name]
  id: name
- cardinality: multi
  description: Name of the high level ontology class in which this entity is categorized.
    Corresponds to the label for the biolink entity type class. In a neo4j database
    this MAY correspond to the neo4j label tag
  display_name: !!python/object/new:metamodel.metamodel.SlotDefinitionName [category]
  id: category
- description: A grouping for any relationship type that holds between any two things
  display_name: !!python/object/new:metamodel.metamodel.SlotDefinitionName [related
      to]
  id: related_to
- description: A grouping for any property that holds between a node and a value
  display_name: !!python/object/new:metamodel.metamodel.SlotDefinitionName [node property]
  id: node_property
- description: An IRI for the node. This is determined by the id using expansion rules.
  display_name: !!python/object/new:metamodel.metamodel.SlotDefinitionName [iri]
  id: iri
- description: a long-form human readable name for a thing
  display_name: !!python/object/new:metamodel.metamodel.SlotDefinitionName [full name]
  id: full_name
- description: a human-readable description of a thing
  display_name: !!python/object/new:metamodel.metamodel.SlotDefinitionName [description]
  id: description
- description: more commonly used for gene symbols in yeast
  display_name: !!python/object/new:metamodel.metamodel.SlotDefinitionName [systematic
      synonym]
  id: systematic_synonym
- description: 'holds between a biological entity and a phenotype, where a phenotype
    is construed broadly as any kind of quality of an organism part, a collection
    of these qualities, or a change in quality or qualities (e.g. abnormally increased
    temperature). '
  display_name: !!python/object/new:metamodel.metamodel.SlotDefinitionName [has phenotype]
  id: has_phenotype
- description: connects a thing to a class representing a taxon
  display_name: !!python/object/new:metamodel.metamodel.SlotDefinitionName [in taxon]
  id: in_taxon
- description: holds between a disease or phenotypic feature and a measurable molecular
    entity that is used as an indicator of the presence or state of the disease or
    feature.
  display_name: !!python/object/new:metamodel.metamodel.SlotDefinitionName [correlated
      with]
  id: correlated_with
- description: holds between a disease or phenotypic feature and a measurable molecular
    entity that is used as an indicator of the presence or state of the disease or
    feature.
  display_name: !!python/object/new:metamodel.metamodel.SlotDefinitionName [has biomarker]
  id: has_biomarker
- description: 'holds between a disease or phenotypic feature and a therapeutic process
    or chemical substance that is used to treat the condition '
  display_name: !!python/object/new:metamodel.metamodel.SlotDefinitionName [treated
      by]
  id: treated_by
id: disease_or_phenotypic_feature
schema_generating: true
weight: 20
