description: A relationship between two anatomical entities where the relationship
  is ontogenic, i.e the two entities are related by development. A number of different
  relationship types can be used to specify the precise nature of the relationship
display_name: !!python/object/new:metamodel.metamodel.ClassDefinitionName [anatomical
    entity to anatomical entity ontogenic association]
document_category: !!python/object/new:metamodel.metamodel.ClassDefinitionName [anatomical
    entity to anatomical entity ontogenic association]
fields:
- description: A unique identifier for an association
  display_name: !!python/object/new:metamodel.metamodel.SlotDefinitionName [association_id]
  id: id
- description: if set to true, then the association is negated i.e. is not true
  display_name: !!python/object/new:metamodel.metamodel.SlotDefinitionName [negated]
  id: negated
- description: connects an association to the type of association (e.g. gene to phenotype)
  display_name: !!python/object/new:metamodel.metamodel.SlotDefinitionName [association
      type]
  id: association_type
- cardinality: multi
  description: connects an association to qualifiers that modify or qualify the meaning
    of that association
  display_name: !!python/object/new:metamodel.metamodel.SlotDefinitionName [qualifiers]
  id: qualifiers
- cardinality: multi
  description: connects an association to publications supporting the association
  display_name: !!python/object/new:metamodel.metamodel.SlotDefinitionName [publications]
  id: publications
- description: connects an association to the agent (person, organization or group)
    that provided it
  display_name: !!python/object/new:metamodel.metamodel.SlotDefinitionName [provided
      by]
  id: provided_by
- description: any slot that relates an association to another entity
  display_name: !!python/object/new:metamodel.metamodel.SlotDefinitionName [association
      slot]
  id: association_slot
- description: the structure at a later time
  display_name: !!python/object/new:metamodel.metamodel.SlotDefinitionName [anatomical
      entity to anatomical entity ontogenic association subject]
  id: subject
- description: the structure at an earlier time
  display_name: !!python/object/new:metamodel.metamodel.SlotDefinitionName [anatomical
      entity to anatomical entity ontogenic association object]
  id: object
- description: the relationship type by which a subject is connected to an object
    in an association
  display_name: !!python/object/new:metamodel.metamodel.SlotDefinitionName [anatomical
      entity to anatomical entity ontogenic association relation]
  id: relation
id: anatomical_entity_to_anatomical_entity_ontogenic_association
schema_generating: true
weight: 20
