description: Either an individual molecular activity, or a collection of causally
  connected molecular activities
display_name: !!python/object/new:metamodel.metamodel.ClassDefinitionName [biological
    process or activity]
document_category: !!python/object/new:metamodel.metamodel.ClassDefinitionName [biological
    process or activity]
fields:
- description: A unique identifier for a thing. Must be either a CURIE shorthand for
    a URI or a complete URI
  display_name: !!python/object/new:metamodel.metamodel.SlotDefinitionName [id]
  id: id
- description: A human-readable name for a thing
  display_name: !!python/object/new:metamodel.metamodel.SlotDefinitionName [name]
  id: name
- cardinality: multi
  description: Name of the high level ontology class in which this entity is categorized.
    Corresponds to the label for the biolink entity type class. In a neo4j database
    this MAY correspond to the neo4j label tag
  display_name: !!python/object/new:metamodel.metamodel.SlotDefinitionName [category]
  id: category
- description: URI expansion of CURIE
  display_name: !!python/object/new:metamodel.metamodel.SlotDefinitionName [uri]
  id: uri
- description: A grouping for any relationship type that holds between any two things
  display_name: !!python/object/new:metamodel.metamodel.SlotDefinitionName [related
      to]
  id: related_to
- description: A grouping for any property that holds between a node and a value
  display_name: !!python/object/new:metamodel.metamodel.SlotDefinitionName [node property]
  id: node_property
- description: An IRI for the node. This is determined by the id using expansion rules.
  display_name: !!python/object/new:metamodel.metamodel.SlotDefinitionName [iri]
  id: iri
- description: a long-form human readable name for a thing
  display_name: !!python/object/new:metamodel.metamodel.SlotDefinitionName [full name]
  id: full_name
- description: a human-readable description of a thing
  display_name: !!python/object/new:metamodel.metamodel.SlotDefinitionName [description]
  id: description
- description: more commonly used for gene symbols in yeast
  display_name: !!python/object/new:metamodel.metamodel.SlotDefinitionName [systematic
      synonym]
  id: systematic_synonym
- description: 'holds between a biological entity and a phenotype, where a phenotype
    is construed broadly as any kind of quality of an organism part, a collection
    of these qualities, or a change in quality or qualities (e.g. abnormally increased
    temperature). '
  display_name: !!python/object/new:metamodel.metamodel.SlotDefinitionName [has phenotype]
  id: has_phenotype
id: biological_process_or_activity
schema_generating: true
weight: 20
