description: Any association between a genotype and a sequence variant.
display_name: !!python/object/new:metamodel.metamodel.ClassDefinitionName [genotype
    to variant association]
document_category: !!python/object/new:metamodel.metamodel.ClassDefinitionName [genotype
    to variant association]
fields:
- description: A unique identifier for an association
  display_name: !!python/object/new:metamodel.metamodel.SlotDefinitionName [association_id]
  id: id
- description: if set to true, then the association is negated i.e. is not true
  display_name: !!python/object/new:metamodel.metamodel.SlotDefinitionName [negated]
  id: negated
- description: connects an association to the type of association (e.g. gene to phenotype)
  display_name: !!python/object/new:metamodel.metamodel.SlotDefinitionName [association
      type]
  id: association_type
- cardinality: multi
  description: connects an association to qualifiers that modify or qualify the meaning
    of that association
  display_name: !!python/object/new:metamodel.metamodel.SlotDefinitionName [qualifiers]
  id: qualifiers
- cardinality: multi
  description: connects an association to publications supporting the association
  display_name: !!python/object/new:metamodel.metamodel.SlotDefinitionName [publications]
  id: publications
- description: connects an association to the agent (person, organization or group)
    that provided it
  display_name: !!python/object/new:metamodel.metamodel.SlotDefinitionName [provided
      by]
  id: provided_by
- description: any slot that relates an association to another entity
  display_name: !!python/object/new:metamodel.metamodel.SlotDefinitionName [association
      slot]
  id: association_slot
- description: the relationship type used to connect genotype to gene
  display_name: !!python/object/new:metamodel.metamodel.SlotDefinitionName [genotype
      to variant association relation]
  id: relation
- description: parent genotype
  display_name: !!python/object/new:metamodel.metamodel.SlotDefinitionName [genotype
      to variant association subject]
  id: subject
- description: gene implicated in genotype
  display_name: !!python/object/new:metamodel.metamodel.SlotDefinitionName [genotype
      to variant association object]
  id: object
id: genotype_to_variant_association
schema_generating: true
weight: 20
