name: Build and Deploy Static Mkdocs Documentation

# Controls when the action will run. Triggers the workflow on pull request
on:
  push:
    branches:
      - master
      - main
    paths:
      - 'mkdocs.yml'
      - 'model/schema/*.yaml'

  repository_dispatch:
    types: trigger-build-deploy-documentation

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  github-pages:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.9

      # Install poetry
      - name: Install poetry
        run: python3 -m pip install --no-cache-dir poetry

      # If cache was not loaded, install dependencies
      - name: Install dependencies
        # if: steps.cache-poetry.outputs.cache-hit != 'true'
        run: poetry install -d

      # generate markdown files
      - run: |
          mkdir docs
          poetry run gen-doc biolink-model.yaml --directory docs --template-directory doc_templates
          cp css/extra_css.css docs
          cp guidelines/*.md docs

      # deploy documentation (note: requires documentation is in docs dir)
      - run: make gh-deploy