name: Build and Deploy Static Mkdocs Documentation

# Controls when the action will run. Triggers the workflow on pull request
on:
  pull_request:
    branches:
      - master
      - main
  push:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  github-pages:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.9

      # Install poetry
      - name: Install poetry
        run: python3 -m pip install --no-cache-dir poetry

      # If cache was not loaded, install dependencies
      - name: Install dependencies
        # if: steps.cache-poetry.outputs.cache-hit != 'true'
        run: poetry install -d

      # generate markdown files
      #----------------------------------------------
      #              run test suite
      #----------------------------------------------
      - name: Run tests
        run: poetry run pytest