---
name: Check Dependencies in Pyproject.toml

# Controls when the action will run.
on:
  pull_request:
    types: [opened, synchronize, reopened]
  workflow_dispatch:   # Allows you to run this workflow manually from the Actions tab
    types: trigger-run-check-dependencies

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python: [ "3.10", "3.11", "3.12", "3.13" ]

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        name: setup python environment
        with:
          python-version: ${{ matrix.python }}

      - name: Install uv
        uses: astral-sh/setup-uv@v3

      # this step we remove and rebuild the uv.lock file to ensure that the tests that follow can be run
      # with the latest dependencies
      - name: Install dependencies
        run: |
          rm -rf uv.lock
          uv sync

      - name: Run tests
        run: |
          make test
