---
name: Publish Python Package

on:
  release:
    types: [created]
  workflow_dispatch:
    types: trigger-pypi-publish

jobs:
  build-n-publish:
    name: Build and publish Python distributions to PyPI
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install uv
        uses: astral-sh/setup-uv@v3

      - name: Build source and wheel archives
        run: uv build

      - name: Publish distribution to PyPI
        uses: pypa/gh-action-pypi-publish@v1.13.0
        with:
          user: __token__
          password: ${{ secrets.PYPI_API_TOKEN }}
